version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: "%(asctime)s.%(msecs)03d - [%(shortpath)38s:%(lineno)03d] - %(levelname)-8s - %(message)s" 
    datefmt: '%H:%M:%S'
  colored_console: 
    (): 'coloredlogs.ColoredFormatter'
    format: "%(asctime)s.%(msecs)03d - [%(shortpath)38s:%(lineno)03d] - %(levelname)-8s - %(message)s" 
    datefmt: '%H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: colored_console
    stream: ext://sys.stdout

  # file_handler:
  #   class: logging.handlers.RotatingFileHandler
  #   level: DEBUG
  #   formatter: simple
  #   filename: debug.log
  #   maxBytes: 10485760 # 10MB
  #   backupCount: 20
  #   encoding: utf8

root:
  level: WARNING
  handlers: []

loggers:
    pose_estimation:
        level: SPAM
        handlers: [console] #, file_handler
        propogate: no
